/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cipher;
public class App {

    public static void encodeDecode(ShiftCipher cipher, String text){
      String encoded = cipher.encode(text);
      String decoded = cipher.decode(encoded);
      System.out.println(text + " got encoded as: "+encoded);
      System.out.println(encoded + " got decoded as: "+decoded);
    }

    public static void main(String[] args) {

      System.out.println("\n*********");
      System.out.println("Test 1");
      String text = "hello";
      System.out.println("Creating a shift cipher with shift value 2");
      ShiftCipher shift = new ShiftCipher(2);
      encodeDecode(shift, text);

      System.out.println("\n*********");
      System.out.println("Test 2");
      System.out.println("Creating a shift cipher with shift value 1");
      text = "z";
      shift = new ShiftCipher(1);
      encodeDecode(shift, text);
    }
}
