/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final_exam_spring2023;

import final_exam_spring2023.controller.DiceController;
import final_exam_spring2023.model.Dice;

public class App {

	public static void main(String[] args) {
		new DiceController(new Dice(6));
	}
}
